image: Visual Studio 2019
configuration: Release
version: '{build}'

install:
- ps: >-
    if ($env:APPVEYOR_REPO_TAG -eq "false")
    {
      $env:COMMIT_DESCRIPTION = git describe --tags
    }
    else
    {
      $env:COMMIT_DESCRIPTION = $env:APPVEYOR_REPO_TAG_NAME
    }

dotnet_csproj:
  patch: true
  file: 'GitHubJwt\GitHubJwt.csproj'
  version: $(commit_description)

before_build:
- ps: Update-AppveyorBuild -Version $env:COMMIT_DESCRIPTION
- ps: Add-AppveyorMessage "Build version is $env:COMMIT_DESCRIPTION"
- cmd: dotnet restore

build:
  project: GitHubJwt.sln

test_script:
  - cmd: dotnet test GitHubJwt.Tests/GitHubJwt.Tests.csproj

artifacts:
- path: '**/*.nupkg'
  name: Nuget Packages

deploy:
- provider: NuGet
  api_key:
    secure: Ya9Mv5wR3N/5sOhBl87z/9EsfjCn2gT6Yta+6AGatapdGlYmU5fslHGLhwBAYlm3
  on:
    appveyor_repo_tag: true
